#!/usr/bin/env bash
set -e

unset PAGER


MY_PRS_QUERY='
{
  getUserPullRequests: search(first: 100, type: ISSUE, query: "author:ingshtrom state:open is:pr org:docker") {
    issueCount
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        ... on PullRequest {
          updatedAt
          createdAt
          title
          url,
          isDraft,
          repository {
            name
          }
        }
      }
    }
  }
  getBotPullRequets: search(first: 100, type: ISSUE, query: "author:app/infra-create-pr-exec-action state:open is:pr org:docker") {
    issueCount
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        ... on PullRequest {
          updatedAt
          createdAt
          title
          url,
          isDraft,
          repository {
            name
          }
        }
      }
    }
  }
}

'
MY_PRS_TEMPLATE='
{{- range $pr := .data.getUserPullRequests.edges -}}
  {{- if $pr.node.isDraft -}}
    {{- (printf "--DRAFT-- %s - %v\n" $pr.node.title $pr.node.url) | color "white+d" -}}
  {{- else -}}
    {{- (printf "%s - %v\n" $pr.node.title $pr.node.url) | color "green+b" -}}
  {{- end -}}
{{- end -}}
{{- range $pr := .data.getBotPullRequets.edges -}}
  {{- if $pr.node.isDraft -}}
    {{- (printf "--DRAFT-- %s - %v\n" $pr.node.title $pr.node.url) | color "white+d" -}}
  {{- else -}}
    {{- (printf "%s - %v\n" $pr.node.title $pr.node.url) | color "green+b" -}}
  {{- end -}}
{{- end -}}
'

MY_REVIEWS_QUERY='
{
  search(first: 100, type: ISSUE, query: "is:pr is:open sort:updated-desc review-requested:@me org:docker") {
    issueCount
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        ... on PullRequest {
          updatedAt
          createdAt
          title
          url,
          isDraft,
          repository {
            name
          }
        }
      }
    }
  }
}
'
MY_REVIEWS_TEMPLATE='
{{- range $pr := .data.search.edges -}}
  {{- if $pr.node.isDraft -}}
    {{- (printf "--DRAFT-- %s - %v\n" $pr.node.title $pr.node.url) | color "white+d" -}}
  {{- else -}}
    {{- (printf "%s - %v\n" $pr.node.title $pr.node.url) | color "green+b" -}}
  {{- end -}}
{{- end -}}
'

echo "--------------------------------------------------"
echo;
echo "# Current Pull Requests"
echo;
gh api graphql -f query="${MY_PRS_QUERY}" --paginate --template="${MY_PRS_TEMPLATE}"
echo;
echo "--------------------------------------------------"
echo;
echo "# Current Review Requests"
echo;

gh api graphql -f query="${MY_REVIEWS_QUERY}" --paginate --template="${MY_REVIEWS_TEMPLATE}"
echo;
echo "--------------------------------------------------"
